### ISSUE TITLE
quantnuclei: Error message even though pipeline is running

### ISSUE THREAD

**Issue by carlacohen** [cribbslab/scflow#89]
I've got the scflow main quantnuclei pipeline to run. However the pipeline.log always ends with the following error message, regardless of what part of the pipeline was running. The outputs are all there as expected. I think it's possibly to do with the conda env? 

Error from pipeline.log
`                                                 \
                                            Original exception: \
                                             \
                                                Exception #1 \
                                                  '<class 'TypeError'>handle_sigint() got multiple values for argument 'pool'' raised in ... \
                                                Traceback (most recent call last): \
                                                  File "/home/c/ccohen/conda/obds_conda/envs/scflow/lib/python3.8/site-packages/ruffus/task.py", line 5250, in pipeline_run \
                                                    job_result = ii.next(**itr_kwargs) \
                                                  File "src/gevent/_imap.py", line 105, in gevent._gevent_c_imap.IMapUnordered.__next__ \
                                                  File "src/gevent/_imap.py", line 113, in gevent._gevent_c_imap.IMapUnordered._inext \
                                                  File "src/gevent/queue.py", line 350, in gevent._gevent_cqueue.Queue.get \
                                                  File "src/gevent/queue.py", line 327, in gevent._gevent_cqueue.Queue._Queue__get_or_peek \
                                                  File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get \
                                                  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch \
                                                  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch \
                                                  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch \
                                                  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch \
                                                TypeError: handle_sigint() got multiple values for argument 'pool' \
                                                 \

2023-03-10 08:58:50,243 ERROR main control - end of all error messages
`
                                              

Error from nohup.out
`Original exception:

    Exception #1
      '<class 'TypeError'>handle_sigint() got multiple values for argument 'pool'' raised in ...
    Traceback (most recent call last):
      File "/home/c/ccohen/conda/obds_conda/envs/scflow/lib/python3.8/site-packages/ruffus/task.py", line 5250, in pipeline_run
        job_result = ii.next(**itr_kwargs)
      File "src/gevent/_imap.py", line 105, in gevent._gevent_c_imap.IMapUnordered.__next__
      File "src/gevent/_imap.py", line 113, in gevent._gevent_c_imap.IMapUnordered._inext
      File "src/gevent/queue.py", line 350, in gevent._gevent_cqueue.Queue.get
      File "src/gevent/queue.py", line 327, in gevent._gevent_cqueue.Queue._Queue__get_or_peek
      File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
      File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
      File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
      File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
      File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
    TypeError: handle_sigint() got multiple values for argument 'pool'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/c/ccohen/conda/obds_conda/envs/scflow/bin/scflow", line 33, in <module>
    sys.exit(load_entry_point('scflow', 'console_scripts', 'scflow')())
  File "/ceph/project/tendonhca/ccohen/git/scflow/scpipelines/entry.py", line 104, in main
    module.main(sys.argv)
  File "/ceph/project/tendonhca/ccohen/git/scflow/scpipelines/pipeline_quantnuclei.py", line 269, in main
    P.main(argv)
  File "/home/c/ccohen/conda/obds_conda/envs/scflow/lib/python3.8/site-packages/cgatcore/pipeline/control.py", line 1528, in main
    run_workflow(args)
  File "/home/c/ccohen/conda/obds_conda/envs/scflow/lib/python3.8/site-packages/cgatcore/pipeline/control.py", line 1458, in run_workflow
    raise ValueError("pipeline failed with errors") from ex
ValueError: pipeline failed with errors
`

**Comment by Acribbs** [comment]
yes this is likely related to how you installed scflow.

Message is cryptic but relates to gevent API and I would have to look into source code to work out exaclty. Wonder if you have older packages installed that are incompatible.

Can you also run with `--local` and let me know if you get same issues?

**Comment by carlacohen** [comment]
I ran 
`nohup scflow main quantnuclei make full -v5 --local`
This time there was no error message
